### ISSUE TITLE
RuntimeError in training a model of resnet152 using transfer learning: "models cannot register a hook on a tensor that doesn't require gradient"

### ISSUE THREAD

**Issue by FurkanArslan** [aws/sagemaker-pytorch-training-toolkit#197]
Hi,

I am struggling with a strange error in my transfer learning model. The pytorch estimator is giving **RuntimeError: cannot register a hook on a tensor that doesn't require gradient** error both on GPU and CPU sagemaker instances. I cannot find any solution for this error.

```
Traceback (most recent call last):
  File "run_aws.py", line 159, in 
    _train(parser.parse_args())
  File "run_aws.py", line 116, in _train
    log_interval=log_interval
  File "/opt/ml/code/trainer.py", line 25, in fit
    train_loss, metrics = train_epoch(train_loader, model, loss_fn, optimizer, cuda, log_interval, metrics)
  File "/opt/ml/code/trainer.py", line 61, in train_epoch
    outputs = model(*data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 531, in _call_
    hook.register_hook(self)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 194, in register_hook
    self.register_module(module)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 227, in register_module
    self._backward_apply(module)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 186, in _backward_apply
    param.register_hook(self.backward_hook(pname))
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 227, in register_hook
    raise RuntimeError("cannot register a hook on a tensor that "
RuntimeError: cannot register a hook on a tensor that doesn't require gradient
```

My notebook codes are below:

```
import sagemaker
import os

from sagemaker.pytorch import PyTorch

sagemaker_session = sagemaker.Session()

# Define IAM role
role = sagemaker.get_execution_role()

bucket = 'shoe-dataset'
prefix = 'sagemaker/singleColor'

data_location = 's3://{}/{}'.format(bucket, prefix)
!pygmentize run_aws.py

estimator = PyTorch(entry_point='run_aws.py',
                    source_dir='.',
                    role=role,
                    framework_version='1.4.0',
                    train_instance_count=1,
                    train_instance_type='ml.p2.xlarge')

estimator.fit({
    'train': os.path.join(data_location, 'train'), 
    'test': os.path.join(data_location, 'test')
})
```

run_aws.py code is here: 
https://github.com/FurkanArslan/deep-shoe-implementation/blob/master/run_aws.py

Here is the actual code that gives an error when forwarding the resnet152 model: (line 61):
https://github.com/FurkanArslan/deep-shoe-implementation/blob/master/trainer.py

**Comment by FurkanArslan** [comment]
While searching google, I saw a thread about the same error in the Pytorch forum. I am wondering if the problem is about the estimator is trying to register a hook for parts that don't require grad in the resnet model?

https://discuss.pytorch.org/t/register-hook-throwing-an-error-during-model-eval/65432

**Comment by laurenyu** [comment]
sorry for the delayed response here. I wasn't able to see the code you linked to (the links gave me 404s) - could you paste it here?

The error message suggests that the issue comes from your training code, so the PyTorch forums are probably a better bet for questions like these.

**Comment by laurenyu** [comment]
closing due to lack of activity.
